export const mythicalAnimals = [
    'Ababil',
    'Abaia',
    'Abath',
    'Abatwa',
    'Adlet',
    'Aethon',
    'Afanc',
    'Ahuizotl',
    'Ajatar',
    'Akhlut',
    'Akkorokamui',
    'Al-mi\'raj',
    'Alan',
    'Alectryon',
    'Alicanto',
    'Alkonost',
    'Allocamelus',
    'Amalthea',
    'Amarok',
    'Amefurikozō',
    'Ammit',
    'Ammut',
    'Amphisbaena',
    'Amphithere',
    'Anansi',
    'Androktasiai',
    'Angel',
    'Anggitay',
    'Anubis',
    'Anzû',
    'Apep',
    'Arachne',
    'Argus Panoptes',
    'Aries',
    'Arion',
    'Asena',
    'Aspidochelone',
    'Asteria',
    'Asura',
    'Aswang',
    'Auðumbla',
    'Automaton',
    'Axehandle hound',
    'Azeban',
    'Azure Dragon',
    'Baba Yaga',
    'Bahamut',
    'Bai Ze',
    'Bake-kujira',
    'Bakeneko',
    'Bakonawa',
    'Baku',
    'Bakunawa',
    'Balayang',
    'Balor',
    'Banshee',
    'Barbegazi',
    'Bare-fronted Hoodwink',
    'Basan',
    'Basilisk',
    'Bastet',
    'Beast of Bodmin',
    'Beast of Gévaudan',
    'Behemoth',
    'Bennu',
    'Bicorn and Chichevache',
    'Bigfoot',
    'Biscione',
    'Bishop-fish',
    'Black dog',
    'Black Tortoise',
    'Blodeuwedd',
    'Bloody Bones',
    'Błudnik',
    'Blue Mountains panther',
    'Bluecap',
    'Bogeyman',
    'Boggart',
    'Bonnacon',
    'Boto',
    'Brazen head',
    'Brownie',
    'Bugbear',
    'Buggane',
    'Bunyip',
    'Buraq',
    'Cactus cat',
    'Cai Cai-Vilu',
    'Cait Sidhe',
    'Caladrius',
    'Callisto',
    'Calydonian Boar',
    'Camazotz',
    'Camenae',
    'Capricorn',
    'Capricornus',
    'Carbuncle',
    'Carbunclo',
    'Cath Palug',
    'Catoblepas',
    'Ceffyl Dŵr',
    'Centaur',
    'Cerberus',
    'Ceryneian Hind',
    'Cetan',
    'Cetus',
    'Chalkydri',
    'Chamrosh',
    'Charybdis',
    'Cherub',
    'Cherufe',
    'Cheval Gauvin',
    'Cheval Mallet',
    'Chimera',
    'Chinese dragon',
    'Chiron',
    'Chol',
    'Chollima',
    'Chonchon',
    'Chronos',
    'Chrysomallos',
    'Chupacabra',
    'Cinnamon bird',
    'Cipactli',
    'Cockatrice',
    'Coi Coi-Vilu',
    'Coi Coi-Vilu|Cai Cai-Vilu',
    'Crinaeae',
    'Crocotta',
    'Cu Sith',
    'Cupid',
    'Curupira',
    'Cyclopes',
    'Cynocephaly',
    'Daemon',
    'Dahu',
    'Davy Jones\' Locker',
    'Death',
    'Deer Woman',
    'Deity',
    'Demon',
    'Demon Cat',
    'Deva',
    'Devil',
    'Devil Bird',
    'Dhampir',
    'Dingonek',
    'Dobhar-chú',
    'Domovoi',
    'Double-headed eagle',
    'Dragon',
    'Dragon King',
    'Dragon|Water Dragon',
    'Draug',
    'Draugr',
    'Drop Bear',
    'Dryad',
    'Duende',
    'Dullahan',
    'Dvergr',
    'Dvorovoi',
    'Dwarf',
    'Dökkálfar',
    'Each uisge',
    'Echidna',
    'Eikþyrnir',
    'Elemental',
    'Elf',
    'Encantado',
    'Ennedi tiger',
    'Erinyes',
    'Eros',
    'Erymanthian Boar',
    'Euryale',
    'Extraterrestrial life|Alien',
    'Fafnir',
    'Fairy',
    'Familiar',
    'Father Time',
    'Faun',
    'Feathered Serpent',
    'Feng Huang',
    'Fenghuang',
    'Fenrir',
    'Fext',
    'Fur-bearing trout',
    'Futakuchi-onna',
    'Galatea',
    'Gallic rooster',
    'Gamayun',
    'Gandabherunda',
    'Gargouille',
    'Gargoyle',
    'Garmr',
    'Garuda',
    'Gashadokuro',
    'Gef',
    'Gelert',
    'Genie',
    'German',
    'Geryon',
    'Ghillie Dhu',
    'Ghost',
    'Ghoul',
    'Giant',
    'Gilled Antelope',
    'Gingerbread man',
    'Gnome',
    'Goblin',
    'Goldhorn',
    'Golem',
    'Gorgon',
    'Green Man',
    'Gremlin',
    'Griffin',
    'Grindylow',
    'Grootslang',
    'Gullinkambi',
    'Haetae',
    'Haizum',
    'Hamadryad',
    'Harionago',
    'Harpy',
    'Heavenly Llama',
    'Heiðrún',
    'Hekatonkheires',
    'Hell Hound',
    'Hellhound',
    'Hibagon',
    'Hipag',
    'Hippocamp',
    'Hippogriff',
    'Hitotsume-kozou',
    'Homunculus',
    'Honey Island Swamp monster',
    'Hoop snake',
    'Horus',
    'Hræsvelgr',
    'Huang Long',
    'Hudhud',
    'Hugin and Munin',
    'Hulder',
    'Huli jing',
    'Hydra',
    'Hysminai',
    'Iara',
    'Ibong Adarna|Adarna',
    'Ichneumon',
    'Ichthyocentaur',
    'Ichthyocentaurs',
    'Ifrit',
    'Ijiraq',
    'Ika-Roa',
    'Incubus',
    'Ipotane',
    'Isonade',
    'Itsumade',
    'Jackalope',
    'Jaculi',
    'Jade rabbit',
    'Japanese raccoon dog',
    'Jasconius',
    'Jengu',
    'Jiangshi',
    'Jiaolong',
    'Jikininki',
    'Jinn',
    'Jormungand',
    'Jorōgumo',
    'Jubokko',
    'Jueyuan',
    'Jörmungandr',
    'Jötunn|Hrimthurs',
    'Jötunn|Jotun',
    'Jötunn|Mountain Giant',
    'Kamaitachi',
    'Kappa',
    'Karkadann',
    'Karkinos',
    'Kelpie',
    'Keres',
    'Khepri',
    'Khnum',
    'Kishi',
    'Kitsune',
    'Knucker',
    'Kobold',
    'Kodama',
    'Kraken',
    'Kua Fu',
    'Kuchisake-onna',
    'Kui',
    'Kumiho',
    'Kurma',
    'Kushtaka',
    'Ladon',
    'Lake monster',
    'Lamassu',
    'Lamia',
    'Lampades',
    'Lampetia',
    'Lavellan',
    'Leib-Olmai',
    'Lemures',
    'Leprechaun',
    'Lernaean Hydra',
    'Lernaean Hydra|Hydra',
    'Leshy',
    'Leutogi',
    'Leviathan',
    'Lich',
    'Lindworm',
    'Ljósálfar',
    'Loch Ness monster',
    'Longma',
    'Lorelei',
    'Loveland frog',
    'Lusca',
    'Lynx',
    'Madame White Snake',
    'Maenad',
    'Magician',
    'Makara',
    'Makhai',
    'Maltese tiger',
    'Manananggal',
    'Mandrake',
    'Mandurugo',
    'Manticore',
    'Mapinguari',
    'Mare',
    'Medusa',
    'Melusine',
    'Meretseger',
    'Merlion',
    'Mermaid',
    'Merman',
    'Merrow',
    'Minokawa',
    'Minotaur',
    'Minyades',
    'Mizuchi',
    'Mokele Mbembe',
    'Mokele-mbembe',
    'Mokumokuren',
    'Mongolian Death Worm',
    'Monopod',
    'Monster',
    'Moon rabbit',
    'Morgens',
    'Mothman',
    'Muc-sheilch',
    'Mugwump',
    'Mujina',
    'Mummy',
    'Myling',
    'Myrmecoleon',
    'Myrmidons',
    'Nachtkrapp',
    'Naga',
    'Naiad',
    'Namazu',
    'Nandi bull',
    'Narasimha',
    'Neck',
    'Nekomata',
    'Nemean lion',
    'Nephele',
    'Nereid',
    'Nereids',
    'Nguruvilu',
    'Níðhöggr',
    'Nine-headed Bird',
    'Ningyo',
    'Noppera-bō',
    'Nuckelavee',
    'Nue',
    'Nukekubi',
    'Nyctimene',
    'Nymph',
    'Näkki',
    'Ogopogo',
    'Ogre',
    'Ondine',
    'Oni',
    'Onocentaur',
    'Onryō',
    'Oozlum bird',
    'Oread',
    'Orthrus',
    'Ouroboros',
    'Owlman',
    'Ox-Head and Horse-Face',
    'Pabilsaĝ',
    'Pamola',
    'Panther',
    'Patupaiarehe',
    'Pegasus',
    'Peluda',
    'Penanggalan',
    'Peng',
    'Penghou',
    'Peryton',
    'Phantom cat',
    'Phoenix',
    'Phonoi',
    'Piasa',
    'Pisces',
    'Pixiu',
    'Poltergeist',
    'Pombero',
    'Ponaturi',
    'Pontianak',
    'Popobawa',
    'Potamoi',
    'Potamus',
    'Preta',
    'Púca',
    'Qilin',
    'Qiqirn',
    'Ra',
    'Raiju',
    'Raijū',
    'Rain Bird',
    'Rainbow crow',
    'Rainbow serpent',
    'Ramidreju',
    'Rat king',
    'Ratatoskr',
    'Redcap',
    'Roc',
    'Rokurokubi',
    'Rooster of Barcelos',
    'Rusalka',
    'Ryujin',
    'Saci',
    'Salamander',
    'Salawa',
    'Salmon of Wisdom',
    'Samebito',
    'Sandman',
    'Sankai',
    'Sarangay',
    'Sarimanok',
    'Sasquatch',
    'Satan',
    'Satori',
    'Satyr',
    'Saumen Kar',
    'Scorpion man',
    'Sea monk',
    'Sea monster',
    'Sea serpent',
    'Sea-lion',
    'Sekhmet',
    'Selket',
    'Selkie',
    'Serpopard',
    'Sewer alligator',
    'Shabti',
    'Shachihoko',
    'Shadow People',
    'Shangyang',
    'Shedu',
    'Shellycoat',
    'Shen',
    'Shesha',
    'Shōjō',
    'Shug Monkey',
    'Sidehill gouger',
    'Sigbin',
    'Silenus',
    'Simurgh',
    'Siren',
    'Sirin',
    'Skeleton',
    'Skin-walker',
    'Skvader',
    'Slavic fairies|Wili',
    'Sleipnir',
    'Sobek',
    'Sphinx',
    'Spirit',
    'Spriggan',
    'Sprite',
    'Stheno',
    'Strix',
    'Stymphalian birds',
    'Succubus',
    'Surrey Puma',
    'Swamp monster',
    'Swan maiden',
    'Taniwha',
    'Tanngrisnir',
    'Tarasque',
    'Taweret',
    'Ten Ten-Vilu',
    'Tengu',
    'Tennin',
    'Thoth',
    'Three-legged bird',
    'Thunderbird',
    'Tiamat',
    'Tikbalang',
    'Tilberi',
    'Tizheruk',
    'Tjinimin',
    'Tokeloshe',
    'Tomte',
    'Triton',
    'Troll',
    'Tsuchigumo',
    'Tsuchinoko',
    'Tsukumogami',
    'Tulpa',
    'Tupilaq',
    'Turul',
    'Tyger',
    'Typhon',
    'Ubume',
    'Uchchaihshravas',
    'Umibōzu',
    'Undead',
    'Underwater panther',
    'Undine',
    'Unicorn',
    'Ushabti',
    'Ushi-oni',
    'Valkyrie',
    'Vampire',
    'Vanara',
    'Vǎrkolak',
    'Vegetable Lamb of Tartary',
    'Vengeful ghost',
    'Vermilion Bird',
    'Vetala',
    'Víðópnir',
    'Vodyanoy',
    'Vucub Caquix',
    'Wanyūdō',
    'Water leaper',
    'Water spirit',
    'Water sprite',
    'Wechuge',
    'Wendigo',
    'Werehyena',
    'Werejaguar',
    'Werewolf',
    'Wewe Gombel',
    'White stag',
    'White Tiger',
    'Wild Hunt',
    'Will o\' the wisp',
    'Wolpertinger',
    'World Elephant',
    'World Tree',
    'World Turtle',
    'Wyvern',
    'Xing Tian',
    'Yacuruna',
    'Yakshini',
    'Yamata no Orochi',
    'Yaoguai',
    'Yatagarasu',
    'Yeren',
    'Yeti',
    'Ymir',
    'Yokai',
    'Yōkai',
    'Yowie',
    'Yuki-onna',
    'Yurei',
    'Zahhak',
    'Zaratan',
    'Zashiki-warashi',
    'Zemepatis',
    'Zhenniao',
    'Zhu Bajie',
    'Zilant',
    'Ziz',
    'Zombie',
    'Zu'
];
